index:
    path: /
    controller: App\Controller\DefaultController::index

contacts:
    path: /contacts
    controller: App\Controller\DefaultController::contacts

quoutes:
    path: /quotes
    controller: App\Controller\DefaultController::quotes

packagist:
    path: /package-info/{name}
    requirements:
        name: .+
    controller: App\Controller\PackageInfoController::index
